application/views/app_views.py
# -*- coding: utf-8 -*
import flask
import flask_login
from sqlalchemy import or_
from ..forms.user_forms import LoginForm
from application.model.app_model import User

mod = flask.Blueprint('application', __name__, url_prefix='/app')


@mod.route('/')
def index():
    return flask.redirect(flask.url_for('application.panel.index'))


@mod.route('/tracking')
@flask_login.login_required
def tracking():
    return 'hola'


@mod.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = False

    if form.validate_on_submit():
        user = User.query.filter(
            or_(User.email == form.username_email.data, User.username == form.username_email.data)).first()

        if user and user.validate_password(form.password.data):
            flask_login.login_user(user)
            _next = flask.request.args.get('next')
            return flask.redirect(_next or flask.url_for('application.index'))
        else:
            error = True

    return flask.render_template('app/login.html', form=form, error=error)


@mod.route('/logout')
@flask_login.login_required
def logout():
    flask_login.logout_user()

    return flask.redirect(flask.url_for('landing.index'))

application/views/landing.py
# -*- coding: utf-8 -*
import flask

mod = flask.Blueprint('landing', __name__)


@mod.route('/')
def index():
    return flask.render_template('landing/index.html')


@mod.route('/about')
def about():
    return 'about'


@mod.route('/contact')
def contact():
    return 'contact'

application/templates/_macros.html
{% macro vertical_menu_item(name, label, url, current_page) %}
    <a href="{{ url }}" class="item {% if name == current_page %}red active{% endif %}">{{ label }}</a>
{% endmacro %}

{% macro panel_url(endpoint='index') %}
    {{ url_for('application.panel.'+endpoint) }}
{% endmacro %}

{% macro profile_url(endpoint='index') %}
    {{ url_for('application.profile.'+endpoint) }}
{% endmacro %}

application/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>OpenHospital - {{ title }}</title>
    {% else %}
        <title>{% block title %}{% endblock %}</title>
    {% endif %}

    {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='bower/semantic/dist/semantic.min.css') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/logo.png') }}">
</head>
<body>
<div class="container" id="main">
    {% block navbar %}{% endblock %}
    {% block content %}{% endblock %}
</div>
{% block footer %}
    <footer class="ui padded center aligned vertical footer segment">
        <a href="http://www.kopimi.com/kopimi" target="_blank">
            <img src="{{ url_for('static', filename='img/kopimi_k.png') }}" alt="kopimi">
        </a>
    </footer>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='bower/jquery/dist/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='bower/semantic/dist/semantic.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% if jscripts %}
        {% for s in jscripts %}
            <script src="{{ url_for('static', filename='js/' + s) }}"></script>
        {% endfor %}
    {% endif %}
{% endblock %}
</body>
</html>

application/templates/layout.html
{% extends 'base.html' %}
{% set filename = 'img/male.png' if current_user.genre == 'M' else 'img/female.png' %}
{% if current_user.is_authenticated %}
    {% set endpoint_home = url_for('application.panel.index') %}
{% else %}
    {% set endpoint_home = url_for('landing.index') %}
{% endif %}
{% block navbar %}
    <nav class="ui stackable menu">
        <div class="item">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Hospital">
        </div>
        <div class="right menu">
            <a href="{{ endpoint_home }}" class="item">Inicio</a>
            <a href="{{ url_for('landing.about') }}" class="item">Acerca</a>
            <a href="{{ url_for('landing.contact') }}" class="item">Contacto</a>
            {% if current_user.is_authenticated %}
                <div class="ui floating dropdown link item" id="user-dropdown">
                    <div class="text">
                        <img src="{{ url_for('static', filename=filename) }}" alt="avatar" class="ui avatar image">
                        {{ current_user.username | upper }}
                    </div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <a href="{{ url_for('application.panel.index') }}" class="item">
                            <i class="dashboard icon"></i> Panel
                        </a>
                        <a class="item" href="{{ url_for('application.profile.index') }}">
                            <i class="user icon"></i> Perfil
                        </a>
                        <a class="item" href="{{ url_for('application.logout') }}">
                            <i class="sign out icon"></i> Salir
                        </a>
                    </div>
                </div>
            {% else %}
                <a href="{{ url_for('application.login') }}" class="item">Ingresar</a>
            {% endif %}
        </div>
    </nav>
{% endblock %}
{% block content %}

{% endblock %}