application/views/landing.py
# -*- coding: utf-8 -*
import flask

mod = flask.Blueprint('landing', __name__)


@mod.route('/')
def index():
    return flask.render_template('landing/index.html')


@mod.route('/about')
def about():
    return 'about'


@mod.route('/contact')
def contact():
    return 'contact'

application/templates/app/dashboard_layout.html
{% extends 'layout.html' %}
{% block content %}
    <div class="ui grid">
        <div class="three wide column">
            <div class="ui vertical menu">
                {% block vertical_menu %}{% endblock %}

            </div>
        </div>
        <div class="twelve wide column">
            {% block panel_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

application/templates/app/index.html
{% extends 'layout.html' %}

application/templates/app/login.html
{% extends 'base.html' %}
{% block title %}Ingresar{% endblock %}
{% block css %}
    {{ super() }}
    <style>
        body > .grid {
            height: 75%;
        }

        .column {
            max-width: 450px;
        }

        .home-link {
            color: #000;
        }

        .home-link:hover {
            color: #0f2021;
        }
    </style>
{% endblock %}
{% block content %}

    <div id="content" class="ui middle aligned center aligned grid">
        <div class="column">
            <a href="{{ url_for('landing.index') }}" title="Volver al inicio" class="home-link"><i
                    class="huge home icon"></i></a>
            <h2>Ingresar al sistema</h2>
            <form class="ui form" method="post">
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        {{ form.username_email }}
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        {{ form.password }}
                    </div>
                </div>
                {{ form.hidden_tag() }}
                <input type="submit" class="ui button" value="Ingresar">
            </form>
            {% if error %}
                <div class="ui error message">
                <i class="close icon"></i>
                <div class="header">
                    Correo electrónico o contraseña inválidos.
                </div>
                <p>Verifique sus datos e inténtelo de nuevo</p>
                </div>
            {% endif %}
            {% if form.errors %}
                <div class="ui error message">
                    <i class="close icon"></i>
                    <div class="header">
                        Algunos datos sin inválidos
                    </div>
                    <ul class="list">
                        {% for e in form.errors %}
                            <li>{{ form.errors[e][0] }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="ui message">
                No tiene una cuenta? <a href="mailto:admin@no.one">Contacte al administrador</a>
            </div>
        </div>
    </div>

{% endblock %}