application/views/app_views.py
# -*- coding: utf-8 -*
import flask
import flask_login
from sqlalchemy import or_
from ..forms.user_forms import LoginForm
from application.model.app_model import User

mod = flask.Blueprint('application', __name__, url_prefix='/app')


@mod.route('/')
def index():
    return flask.redirect(flask.url_for('application.panel.index'))


@mod.route('/tracking')
@flask_login.login_required
def tracking():
    return 'hola'


@mod.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = False

    if form.validate_on_submit():
        user = User.query.filter(
            or_(User.email == form.username_email.data, User.username == form.username_email.data)).first()

        if user and user.validate_password(form.password.data):
            flask_login.login_user(user)
            _next = flask.request.args.get('next')
            return flask.redirect(_next or flask.url_for('application.index'))
        else:
            error = True

    return flask.render_template('app/login.html', form=form, error=error)


@mod.route('/logout')
@flask_login.login_required
def logout():
    flask_login.logout_user()

    return flask.redirect(flask.url_for('landing.index'))

application/views/landing.py
# -*- coding: utf-8 -*
import flask

mod = flask.Blueprint('landing', __name__)


@mod.route('/')
def index():
    return flask.render_template('landing/index.html')


@mod.route('/about')
def about():
    return 'about'


@mod.route('/contact')
def contact():
    return 'contact'

application/templates/landing/index.html
{% extends "layout.html" %}

{% block title %}Bienvenido{% endblock %}

{% block content %}
    <div class="ui segments">
        <div class="ui vertical stripe segment">
            <div class="ui middle aligned stackable grid container">
                <div class="row">
                    <div class="eight wide column">
                        <h3 class="ui header">Elimine los pormenores en la admnistración de su hospital</h3>
                        <p>Permítanos administrador los detalles engorrosos de su hospital
                            mientras usted se dedica a brindarle un asistencia personalizada a sus clientes.</p>
                    </div>
                    <div class="six wide right floated column">
                        <img src="{{ url_for('static', filename='img/cover.jpg') }}"
                             class="ui large bordered rounded image">
                    </div>
                </div>
                <div class="row">
                    <div class="right aligned column">
                        <a href="{{ url_for('application.login') }}" class="ui huge green button">
                            <i class="dashboard icon"></i> Ingresar
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="ui vertical stripe segment">
            <div class="ui middle aligned stackable grid container">
                <div class="row">
                    <div class="six wide column">
                        <img src="{{ url_for('static', filename='img/tracking.png') }}" alt="Seguimiento">
                    </div>
                    <div class="eight wide right floated column">
                        <h3 class="ui header">Seguimiento en línea de ambulancias</h3>
                        <p>Revise las emergencias que están siendo atendidas por nuestras unidades en tiempo real.
                            No se pierda ni un solo detalle de los destinos y las emergencias atendidas por las
                            ambulancias</p>
                    </div>
                </div>
                <div class="row">
                    <div class="left aligned column">
                        <a href="{{ url_for('application.tracking') }}" class="ui huge red button">
                            <i class="ambulance icon"></i> Seguimiento
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="ui vertical stripe segment">
            <div class="ui middle aligned stackable grid container">
                <div class="row">
                    <div class="eight wide column">
                        <h3 class="ui header">Disponibilidad garantizada</h3>
                        <p>Nuestro sistema en línea garantiza una disponibilidad inmediata y global para que sus
                            operaciones
                            se encuentren siempre funcionales. Cuando sea y donde sea.</p>
                    </div>
                    <div class="six wide right floated column">
                        <img src="{{ url_for('static', filename='img/worldwide.jpg') }}"
                             class="ui large bordered rounded image">
                    </div>
                </div>
                <div class="row">
                    <div class="right aligned column">
                        <a href="{{ url_for('landing.contact') }}" class="ui huge blue button">
                            <i class="call icon"></i> Contactar
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="ui vertical stripe segment">
            <div class="ui middle aligned stackable grid container">
                <div class="row">
                    <div class="six wide column">
                        <img src="{{ url_for('static', filename='img/open.jpg') }}" alt="Código libre">
                    </div>
                    <div class="eight wide right floated column">
                        <h3 class="ui header">Gratuito y libre</h3>
                        <p>El código que le da el poder a la aplicación es completamente libre por lo que cualquier
                            persona puede arreglarlo y mejorarlo</p>
                    </div>
                </div>
                <div class="row">
                    <div class="left aligned column">
                        <a href="" class="ui huge gray button">
                            <i class="github icon"></i> Código
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}